### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp.storage#41]
Ahoj Jardo,
na edeposit-aplikace:
```
edeposit-storage:~ # curl http://edeposit-storage.local/UUID/24d7972e164b4bbfafdc96689515e04e                                                                                                                                                                             

    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 500 Internal Server Error</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 500 Internal Server Error</h1>
            <p>Sorry, the requested URL <tt>&#039;http://edeposit-storage.local/UUID/24d7972e164b4bbfafdc96689515e04e&#039;</tt>
               caused an error:</p>
            <pre>Internal Server Error</pre>
        </body>
    </html>
```
(blocks edeposit/edeposit#575)

**Comment by Bystroushaak** [comment]
```
10.5.1.72 - - [22/Sep/2015:17:26:40 +0200] "GET /UUID24d7972e164b4bbfafdc96689515e04e HTTP/1.1" 404 802 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36"
Traceback (most recent call last):
  File "/usr/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/usr/bin/edeposit_storage_server.py", line 197, in fetch_by_uuid
    abort(403, PRIVATE_ACCESS_MSG % (name, uuid))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
```

**Comment by jstavel** [comment]
poslal jsem tam:
http://edeposit-aplikace.nkp.cz/producents/ostre-nakladatelstvi-c-14-2013-souborne-zaznamy/epublications/zavate-doby-se-probouzeji-ii/zavate-doby-ii_producent14.pdf/

**Comment by Bystroushaak** [comment]
Mělo by být vyřešeno. Updatoval jsem balíček a teď prosím o otestování.

**Comment by jstavel** [comment]
uz to funguje. linka:
http://edeposit-aplikace.nkp.cz/@@redirect-to-accessing/24d7972e164b4bbfafdc96689515e04e

![image](https://cloud.githubusercontent.com/assets/2276410/10023225/42d5790c-6151-11e5-8d17-eca799c0b0d3.png)

**Comment by jstavel** [comment]
Tohle muzeme uzavrit. Diky!

**Comment by jstavel** [comment]
dneska byl uspesny den!
